(define (largest-smallest lista)
  (let ((h (car lista)))
    (if (null? (cdr lista))
        (list h h)
        (let ((rec (largest-smallest (cdr lista))))
          (list (max h (car rec)) (min h (cadr rec)))
        )
    )
  )
)
