(define (search-replace lista a b)
  (if (null? lista)
    '()
    (let ((r (search-replace (cdr lista) a b)) (h (car lista)))
      (if (list? h)
        (cons (search-replace h a b) r)
        (cons (if (eqv? h a) b h) r)
      )
    )
  )
)
