(define (search-remove x lista)
  (if (null? lista)
    '()
    (let ((r (search-remove x (cdr lista))) (h (car lista)))
      (if (list? h)
        (cons (search-remove x h) r)
        (if (eqv? h x) r (cons h r))
      )
    )
  )
)
